### ISSUE TITLE
adding autocompletion for multirust

### ISSUE THREAD

**Issue by chyzwar** [brson/multirust#108]
Hi

Something like that: http://www.linuxjournal.com/content/more-using-bash-complete-command 
nvm for node.js have it :https://github.com/creationix/nvm/blob/master/bash_completion

**Comment by brson** [comment]
Thanks for the feature request. I'd accept a patch that added this.

**Comment by chyzwar** [comment]
ok, I will try.

**Comment by chyzwar** [comment]
Made a pull request. take a look.
