### ISSUE TITLE
multirust doc could take a `<toolchain>` argument

### ISSUE THREAD

**Issue by tbu-** [brson/multirust#111]
```
multirust doc [<toolchain>] [--all]
```

Opens the doc of the currently active toolchain if none is specified in the command line.

**Comment by brson** [comment]
`<toolchain>' sounds good to me. Not sure about`--all` - not clear what it means with certain possible output types, how useful it is.

**Comment by tbu-** [comment]
To be honest, I only included `--all` because it already is a command line parameter. I neither need it nor do I like the naming. If you want to keep it, renaming it to something like `--index` might be good, I don't care. I would like to have a `[<toolchain>]` optional parameter though. :)

**Comment by brson** [comment]
Oh, wow. I was just guessing what `--all` did! Nah, let's just leave it doing what it does for now.

**Comment by tbu-** [comment]
This tools is not developed anymore, so I could close this issue, right?
