### ISSUE TITLE
Allow configuration of `.multirust` directory location.

### ISSUE THREAD

**Issue by Hoverbear** [brson/multirust#119]
Sometimes it's rather inconvenient to have folders in `$HOME`, especially when doing this like automated building as I discovered while working on a [Heroku Buildpack](https://hoverbear.org/2016/01/04/Heroku-Rust-Buildpack/).

I'd like to help make it possible to configure where this directory goes. My initial thought is to use `$MULTIRUST_HOME` as `cargo` already has a `$CARGO_HOME` and that seems to be straightforward.

**Comment by Hoverbear** [comment]
Thanks to @thisishugo for pointing out that you can! https://github.com/Hoverbear/heroku-buildpack-rust/pull/17

It'd be good to document this a bit maybe instead?

**Comment by brson** [comment]
multirust.sh uses `MULTIRUST_HOME`.

**Comment by eminence** [comment]
+1 to documenting this feature (perhaps in the 'Manual build, install and configure' section of the README)
