### ISSUE TITLE
Update message breaks usage with cargo

### ISSUE THREAD

**Issue by zargony** [brson/multirust#12]
When a new version is available, multirust outputs a message that confuses cargo's dylib prefix/suffix discovery. Maybe multirust should output messages to stderr or entirely skip the message if --print is used with rustc.

```
$ cargo test --verbose
multirust: a new version of 'nightly' is available. run `multirust update nightly` to install it
thread '<main>' panicked at 'rustc --print-file-name output has changed', src/cargo/ops/cargo_rustc/context.rs:110
```

**Comment by brson** [comment]
Thanks! multirust skips the update message if --verbose is printed. Seems like this is another case.

I was worried about this kind of breakage.
