### ISSUE TITLE
blastoff.sh renaming breaks my build scripts

### ISSUE THREAD

**Issue by Fiedzia** [brson/multirust#134]
This is a rant, so feel free to just close, but I want to say it:

I was relying to download this exact url in my docker build scripts:
https://raw.githubusercontent.com/brson/multirust/master/blastoff.sh
and suddenly its broken. Multirust is becoming part of people infrastructure,
so please do not break urls willy-nilly without good reason, grace period,
and public announcement. Ideally do not break them ever.

**Comment by brson** [comment]
You are right. It was a poorly considered change, and I apologize.

**Comment by brson** [comment]
I've reverted the name change, while also leaving `quick-install.sh` for compatibility. Both should work now.

**Comment by Fiedzia** [comment]
Great, thanks for understanding.
