### ISSUE TITLE
multirust installed with brew does not support add-target

### ISSUE THREAD

**Issue by yanns** [brson/multirust#149]
I installed `multirust` with `brew`.

```
multirust --version
multirust 0.7.0 (b222fcd27 2015-09-24 10:53:38 -0700)
```

So the last release 0.7 is installed (https://github.com/brson/multirust/releases)

But the installed version does not support `add-target`.

```
multirust help add-target

multirust: unrecognized topic 'help-add-target'
```

Error in the `brew`package, or the last release is too old?

**Comment by brson** [comment]
Hm, I thought I had tagged 0.8, but I have now. Is that sufficient for homebrew to update itself?

**Comment by yanns** [comment]
```
brew upgrade
==> Upgrading 1 outdated package, with result:
multirust 0.8.0
```

```
multirust help add-target
# Adds the standard library for a given platform to an existing
# installation.
#
# Usage:
#     multirust add-target <toolchain> <triple>
#
```

Thx!
