### ISSUE TITLE
uninstall does not work

### ISSUE THREAD

**Issue by fneddy** [brson/multirust#152]
trying to uninstall multirust failes with `blastoff: failed to uninstall multirust`:

```
~ > cargo --version
cargo 0.10.0-nightly (d38f03b 2016-03-29)
~ > rustc --version
rustc 1.9.0-nightly (b678600ac 2016-03-29)
~ >multirust --version
multirust 0.7.0 (b222fcd27 2015-09-24 10:53:38 -0700)

~ > curl -sf https://raw.githubusercontent.com/brson/multirust/master/blastoff.sh | sh -s -- --uninstall 
This script will uninstall multirust. It may prompt for your password via 'sudo'.

Ready? (y/N) y

blastoff: working in temporary directory /tmp/tmp.b4NVdxHxx5
blastoff: cloning multirust git repo
Cloning into 'multir ....
... 
blastoff: uninstalling
[sudo] password for eddy: 
install: error: unable to find installation manifest at /usr/local/lib/rustlib
blastoff: failed to uninstall multirust
~ > 
```

**Comment by brson** [comment]
Weird! Do you have _anything_ in `/usrc/local/lib/rustlib`? Can you list the directory contents perhaps?

**Comment by fneddy** [comment]
there is just an install.log with the error msg in it:

```
~> ls -la /usr/local/lib/rustlib
total 2
drwxr-xr-x 2 root root  3 Mar 30 21:24 .
drwxr-xr-x 3 root root  3 Mar 30 21:24 ..
-rw-r--r-- 1 root root 79 Mar 30 21:24 install.log

~> cat /usr/local/lib/rustlib/install.log
install: error: unable to find installation manifest at /usr/local/lib/rustlib
```

**Comment by brson** [comment]
Is there a chance that you installed rustc in some other way, not with multirust? Where is your `rustc` binary located? Multirust uninstall would expect it to be at `/usr/local/bin/rustc`.

**Comment by edoput** [comment]
Same error for me, rustc is installed in `/home/edoput/.cargo/bin/rustc` and I should have used multirust to install it IIRC

**Comment by klingtnet** [comment]
Double check that you've installed multirust with the `blastoff` script (`curl | sh`), because I got the same error until I realised that I installed `multirust` with `pacman`. :bulb:

**Comment by brson** [comment]
@EdoPut multirust doesn't put things in `.cargo/bin`. That looks more like [rustup](https://github.com/rust-lang-nursery/rustup.rs).

**Comment by edoput** [comment]
Sounds ok, I already run the multirust uninstall script from  `/usr/local/lib/rustlib/uninstall.sh` and multirust kept functioning from `~/edoput/.cargo/bin/multirust` even without the directory `/usr/local/lib/rustlib`. I removed the multirust binary and now it looks good to me.
