### ISSUE TITLE
error updating nightly toolchain

### ISSUE THREAD

**Issue by alexreg** [brson/multirust#35]
The checksum seems to fail...

https://gist.github.com/83a5dec72a7d38c001af

Any idea about this? Even a work-around would be nice, since this is kind of inhibitive to my Rust development right now.

Thanks!

**Comment by brson** [comment]
This is a result of https://github.com/rust-lang/rust/issues/21239, our CDN not syncing correctly. If GPG is installed multirust will not use the CDN and avoid this problem.
