### ISSUE TITLE
Add a way to get the path to the real rustc

### ISSUE THREAD

**Issue by brson** [brson/multirust#36]
@pnkfelix suggested `rustc --which` might just print the path to rustc so people could e.g. write `rust-gdb $(rustc --which)`.

Not sure I like intercepting arguments to rustc like that though. Maybe `multirust which rustc`.

**Comment by nodakai** [comment]
I think you can close this ticket, because `multirust which` together with a basic error check was already merged.

**Comment by brson** [comment]
Thanks for the triage!
