### ISSUE TITLE
fallback to sha256sum if shasum does not exist

### ISSUE THREAD

**Issue by brson** [brson/multirust#39]
There doesn't seem to be an implementation of sha256 that one can depend on being available everywhere.

**Comment by jarod** [comment]
On CentOS 6 shasum is in package perl-Digest-SHA-PurePerl. This take me some time to find out. Hope this comment can save time for someone else

```
blastoff: installing nightly toolchain
multirust: need shasum
```

**Comment by brson** [comment]
This is done.
