### ISSUE TITLE
multirust update all

### ISSUE THREAD

**Issue by reem** [brson/multirust#46]
Updates all currently installed toolchains, e.g. `nightly` and `beta` all in one go.

Alternatively, have `multirust update nightly beta ...` work.

**Comment by brson** [comment]
I might want this to be `multirust update-all` since `multirust update all` requires special-casing 'all' as a toolchain name. Or maybe `multirust update` can just update nightly/beta/stable.

**Comment by reem** [comment]
I would be happy with any of those.

**Comment by SimonSapin** [comment]
Fixed in a0b7da4bdf4fca09e49d784c16cf3666301a86c9, can be closed.

**Comment by reem** [comment]
Yay!
