### ISSUE TITLE
Can not reinstall a toolchain after removing it

### ISSUE THREAD

**Issue by SimonSapin** [brson/multirust#53]
To reproduce:

``` sh
multirust update beta
multirust remove-toolchain beta
multirust update beta
```

Expected result: the last command downloads and installs Rust beta

Actual result: the last command does nothing. Its output includes `rustup: 'beta' is already up to date`.

Work around: remove the `$MULTIRUST_HOME/update-hashes/beta` file. `remove-toolchain` should do this.

**Comment by brson** [comment]
Thanks for the report.

**Comment by brson** [comment]
Fixed.
