### ISSUE TITLE
Tag & provide a tar.gz to be able to have a homebrew recipy ...

### ISSUE THREAD

**Issue by spastorino** [brson/multirust#57]
So I wonder if you can tag the latest version and provide a tar.gz file so we can have a homebrew recipy for multirust.

For more info https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#stable-versions

**Comment by brson** [comment]
Done: https://github.com/brson/multirust/archive/0.0.5.tar.gz

**Comment by spastorino** [comment]
Thanks, added the recipy https://github.com/Homebrew/homebrew/pull/39224 let's see what they say.
