### ISSUE TITLE
Add to homebrew

### ISSUE THREAD

**Issue by brson** [brson/multirust#8]
To make maintenance hands-off I might just have the homebrew recipe defer to blastoff.sh

**Comment by ghost** [comment]
+1

I think a big issue will be to remove multirust's dependency on users running it with sudo, as this is something that homebrew has typically tried to avoid formula's doing as much as possible.

**Comment by felipesere** [comment]
Why does multirust need sudo right now? I haven't looked, but is it required by the install location?

**Comment by brson** [comment]
Multirust doesn't need to run with sudo, but by default it installs itself to /usr/local/, which usually needs root to write to. The blastoff.sh script, which is the recommended way to install multirust, uses sudo to invoke the installer, but the `build.sh` and `install.sh` scripts do not. If homebrew can install things without sudo, then multirust should be perfectly compatible.

To avoid coupling the homebrew recipe to the build and install scripts we might add more options to `blastoff.sh` to avoid the sudo call.

**Comment by passcod** [comment]
As a point of interest, I currently maintain the Arch Linux package for multirust:
https://aur.archlinux.org/packages/multirust/

**Comment by marcbowes** [comment]
https://github.com/Homebrew/homebrew/commit/73c4b815d43ba9d9fe645ebed89e3814aac272a7 seems to fixed this?

**Comment by brson** [comment]
@marcbowes Seems like it, though that revision is quite old.

**Comment by marcbowes** [comment]
Yep. That's when it was introduced. Are you happy with how this was done (aka can this issue be resolved or should we update it to include information about why it is not resolved)?

**Comment by brson** [comment]
Yes, it looks fine. Thanks for investigating.
