### ISSUE TITLE
Stop using -C rpath

### ISSUE THREAD

**Issue by brson** [brson/multirust#96]
It doesn't work on windows, and the upstream implementation doesn't work the way I remembered (it doesn't encode absolute paths of deps). Instead of fixing upstream, let's just accept that using dynamic linking in Rust sucks and discourage it hard.

**Comment by brson** [comment]
cc https://github.com/brson/multirust/issues/43 cc @alexcrichton

**Comment by alexcrichton** [comment]
To me the lack of support on Windows here is killer, otherwise I'd be totally game for fixing the upstream compiler support.
