### ISSUE TITLE
Racer and ctags

### ISSUE THREAD

**Issue by posix4e** [brson/multirust#97]
Certain programs like ctags and racer need a copy of the source code of the rust that multirust was built with. Perhaps it makes sense to allow the user to choose to have the appropriate source checkout into the .multirust directory? What do other people do?

**Comment by brson** [comment]
Yes, this is very much in demand. Source availability is also needed for debugging.

Thanks for the feature request. Closing this in favor of https://github.com/brson/multirust/issues/77.
